# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      files: ^06\. Best practice/
    - id: end-of-file-fixer
      files: ^06\. Best practice/
    - id: check-yaml
      files: ^06\. Best practice/
    - id: check-added-large-files
      files: ^06\. Best practice/

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort (python)
      files: ^06\. Best practice/

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      name: black
      language_version: python3.12
      files: ^06\. Best practice/

# - repo: local
#   hooks:
#     - id: pylint
#       name: pylint
#       entry: pylint
#       language: system
#       types: [python]
#       args: [
#         "-rn",
#         "-sn",
#         "06. Best practice/"
#       ]

- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
      args: [
        "06. Best practice/tests/"
      ]